// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjpdobvpiwfqcfqaduls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqcGRvYnZwaXdmcWNmcWFkdWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NTMyNzQsImV4cCI6MjA5MTEyOTI3NH0.aXRwwWcEdPRhpPMmE6OPhHNay_DDdgawSi4FlQ3yK_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});